In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [5]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(df.Message,df.spam,test_size=0.2)

In [7]:
type(X_train)

pandas.core.series.Series

In [8]:
type(y_train)

pandas.core.series.Series

In [9]:
X_train[:4]

2229                       Those were my exact intentions
2359    I'll talk to the others and probably just come...
5256                    Well she's in for a big surprise!
11      SIX chances to win CASH! From 100 to 20,000 po...
Name: Message, dtype: object

In [10]:
y_train[:4]

2229    0
2359    0
5256    0
11      1
Name: spam, dtype: int64

In [11]:
X_train.shape

(4457,)

In [12]:
y_train.shape

(4457,)

In [13]:
type(X_train.values)

numpy.ndarray

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

v=CountVectorizer()

X_train_cv=v.fit_transform(X_train.values)
X_train_cv

<4457x7715 sparse matrix of type '<class 'numpy.int64'>'
	with 59346 stored elements in Compressed Sparse Row format>

In [15]:
X_train_cv.shape

(4457, 7715)

In [16]:
v.get_feature_names_out()[1000:1050]

array(['anyway', 'anyways', 'anywhere', 'aom', 'apart', 'apartment',
       'apes', 'apeshit', 'aphex', 'apnt', 'apo', 'apologetic',
       'apologise', 'apologize', 'apology', 'app', 'apparently', 'appeal',
       'appear', 'appendix', 'applebees', 'apples', 'application',
       'apply', 'applyed', 'applying', 'appointment', 'appointments',
       'appreciate', 'appreciated', 'approaching', 'appropriate',
       'approve', 'approved', 'approx', 'apps', 'appt', 'appy', 'april',
       'aproach', 'apt', 'aptitude', 'aquarius', 'ar', 'arab', 'arabian',
       'arcade', 'archive', 'ard', 'are'], dtype=object)

In [17]:
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_

In [18]:
v.vocabulary_

{'those': 6848,
 'were': 7437,
 'my': 4653,
 'exact': 2686,
 'intentions': 3693,
 'll': 4150,
 'talk': 6684,
 'to': 6919,
 'the': 6803,
 'others': 4994,
 'and': 957,
 'probably': 5427,
 'just': 3859,
 'come': 1908,
 'early': 2502,
 'tomorrow': 6945,
 'then': 6815,
 'well': 7430,
 'she': 6063,
 'in': 3630,
 'for': 2937,
 'big': 1352,
 'surprise': 6615,
 'six': 6186,
 'chances': 1723,
 'win': 7496,
 'cash': 1677,
 'from': 3018,
 '100': 251,
 '20': 341,
 '000': 1,
 'pounds': 5346,
 'txt': 7077,
 'csh11': 2098,
 'send': 6001,
 '87575': 696,
 'cost': 2025,
 '150p': 300,
 'day': 2180,
 '6days': 595,
 '16': 311,
 'tsandcs': 7047,
 'apply': 1023,
 'reply': 5708,
 'hl': 3438,
 'info': 3661,
 'gonna': 3180,
 'rip': 5785,
 'out': 5003,
 'uterus': 7208,
 'cbe': 1693,
 'is': 3732,
 'really': 5604,
 'good': 3182,
 'nowadays': 4838,
 'lot': 4204,
 'of': 4889,
 'shop': 6096,
 'showrooms': 6123,
 'city': 1822,
 'shaping': 6055,
 'on': 4931,
 'da': 2142,
 'bus': 1573,
 'going': 3170,
 'home': 3462,
 'ok

In [19]:
v.get_feature_names_out()[2107]

'ctxt'

In [20]:
X_train_np=X_train_cv.toarray()
X_train_np[:4][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
import numpy as np

In [22]:
np.where(X_train_np[0]!=0)

(array([2686, 3693, 4653, 6848, 7437], dtype=int64),)

In [23]:
X_train[:4]

2229                       Those were my exact intentions
2359    I'll talk to the others and probably just come...
5256                    Well she's in for a big surprise!
11      SIX chances to win CASH! From 100 to 20,000 po...
Name: Message, dtype: object

In [25]:
X_train[:4][2229]

'Those were my exact intentions'

In [26]:
X_train_np[0][1181]

0

In [27]:
v.get_feature_names_out()[1181]


'ayn'

In [28]:
from sklearn.naive_bayes import MultinomialNB

model=MultinomialNB()

model.fit(X_train_cv,y_train)

MultinomialNB()

In [29]:
X_test_cv=v.transform(X_test)

In [31]:
from sklearn.metrics import classification_report
y_pred=model.predict(X_test_cv)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       959
           1       0.96      0.87      0.91       156

    accuracy                           0.98      1115
   macro avg       0.97      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115



In [32]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)

model.predict(emails_count)

array([0, 1], dtype=int64)

# Using sklearn pipeline

In [33]:
from sklearn.pipeline import Pipeline

clf=Pipeline([
('vectorizer',CountVectorizer()),
('nb',MultinomialNB())
])

In [34]:
clf.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [35]:
y_pred = clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       959
           1       0.96      0.87      0.91       156

    accuracy                           0.98      1115
   macro avg       0.97      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115

